TaskManager/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("tasks.urls", namespace="tasks")),
    path("accounts/", include("django.contrib.auth.urls")),
]

tasks/urls.py
from django.urls import path

from tasks.views import index

urlpatterns = [
    path("", index, name="index"),
]

app_name = "tasks"

tasks/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class Position(models.Model):
    name = models.CharField(max_length=55, unique=True)

    def __str__(self) -> str:
        return f"{self.name}"


class TaskType(models.Model):
    name = models.CharField(max_length=55, unique=True)

    def __str__(self) -> str:
        return f"{self.name}"


class Worker(AbstractUser):
    position = models.ForeignKey(
        to=Position,
        on_delete=models.CASCADE,
        default=1,
    )

    def __str__(self) -> str:
        return f"{self.position} {self.first_name} {self.last_name}"


class Task(models.Model):
    PRIORITY_CHOICES = (
        ("1", "Urgent"),
        ("2", "High"),
        ("3", "Medium"),
        ("4", "Low"),
    )

    name = models.CharField(max_length=55)
    description = models.TextField(blank=True, null=True)
    deadline = models.DateTimeField(blank=True, null=True)
    is_completed = models.BooleanField(default=False)
    priority = models.CharField(
        max_length=1,
        choices=PRIORITY_CHOICES,
        default="3",
    )
    task_type = models.ForeignKey(to=TaskType, on_delete=models.CASCADE)
    assignees = models.ManyToManyField(to=Worker, related_name="tasks", blank=True)

    def __str__(self) -> str:
        return f"{self.name} {self.priority} {self.deadline} {self.is_completed}"

tasks/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render


@login_required
def index(request):
    return render(request, "tasks/index.html")

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% block title %}<title>Taxi Service</title>{% endblock %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
          integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2"
          crossorigin="anonymous">
    <!-- Add additional CSS in static file -->
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>

<body>
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-2">

            {% block sidebar %}
                {% include "includes/sidebar.html" %}
            {% endblock %}

        </div>
        <div class="col-sm-10 ">

            {% block content %}{% endblock %}

        </div>
    </div>
</div>
</body>

</html>

templates/includes/sidebar.html
<ul class="sidebar-nav list-group">
  {% if user.is_authenticated %}
    <li class="list-group-item">User: <a href="{{ user.get_absolute_url }}">{{ user.get_username }}</a></li>
    <li class="list-group-item"><a href="{% url "logout" %}">Logout</a></li>
  {% else %}
    <li class="list-group-item"><a href="{% url "login" %}">Login</a></li>
  {% endif %}

  <br>

  <li class="list-group-item"><a href="{% url 'tasks:index' %}">Home</a></li>

</ul>

templates/tasks/index.html
{% extends "base.html" %}

{% block content %}
    <h1>Taxi Service Home</h1>
    <p>Welcome to Best Taxi Ever!</p>
    <h2>Dynamic content</h2>
    <p>The Taxi service has the following record counts:</p>
    <ul>
        <li><strong>Cars:</strong> {{ num_cars }}</li>
        <li><strong>Drivers:</strong> {{ num_drivers }}</li>
        <li><strong>Manufacturers:</strong> {{ num_manufacturers }}</li>
    </ul>

{% endblock %}